title: "Syd Lonreiro"
description: "Cryonics, thoughts & future prospects"
lang: en-US
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
collections:
  posts:
    output: true
markdown: kramdown
